---
resource_types:

  - name: slack-notifier
    type: docker-image
    source:
      repository: mockersf/concourse-slack-notifier

resources:
  - name: ecs-broker-repo
    type: git
    source:
      uri: ((broker_repo))
      branch: ((broker_branch))
      access_token: ((git_token))

  - name: docker_registry_src
    type: registry-image
    source:
      repository: ((registry_src))
      debug: ((debug))
      tag: ((src_image_tag))  # use latest?
    check_every: 30m

  - name: docker_registry_dest
    type: registry-image
    source:
      repository: ((registry_dest))
      username: ((registry_dest_username))
      password: ((registry_dest_password))
      debug: ((debug))
      tag: green  #is it ok to use this tag for images which successfully passed tests?

#  - name: objectscale-pipelines-repo
#    type: git
#    source:
#      uri: ((pipelines_repo))
#      username: ((registry_dest_username))
#      branch: ((pipelines_branch))
#      password: ((git_token))

  - name: svc-cat-repo
    type: git
    source:
      uri: ((svc_cat_repo))
      branch: ((svc_cat_repo_branch))

  - name: slack-alert
    type: slack-notifier
    source:
      url: ((slack_url))

jobs:

  - name: release-broker-image
    plan:
      - get: docker_registry_src
        params:
          format: oci
        trigger: true

      - in_parallel:
#          - get: objectscale-pipelines-repo
          - get: ecs-broker-repo
          - get: svc-cat-repo

#      - task: install-kind
#        file: ecs-broker-repo/tasks/kind-cmd
#
#      - task: create-kind-clister
#        file: ecs-broker-repo/tasks/kind-cmd

      - in_parallel:
          - task: create-kubeconfig
            file: ecs-broker-repo/ci/tasks/write-file/task.yml
            output_mapping:
              output-folder: config
            params:
              DEBUG: ((debug))
              OUTPUT_FILE_NAME: config
              PARAM_NAME: ((kubeconfig))

          - task: create-broker-values-file    #substitute needed params (sig?)
            file: ecs-broker-repo/ci/tasks/write-file/task.yml    #create new task
            output_mapping:
              output-folder: broker-values
            params:
              DEBUG: ((debug))
#              TEMPLATE_FILE_NAME: values.yml
              OUTPUT_FILE_NAME: broker-values.yml
              PARAM_NAME: ((broker_values))

      - task: install-service-catalog
        file: ecs-broker-repo/ci/tasks/helm-cmd/task.yml
        input_mapping:
          kubeconfig: config
          charts: svc-cat-repo/charts/catalog/
        params:
          DEBUG: ((debug))
          IGNORE_ERROR: true
          COMMAND: install
          CHART: charts/
          RELEASE: service-catalog

      - task: wait-until-ready
        file: ecs-broker-repo/ci/tasks/wait-until-ready/task.yml
        input_mapping:
          kubeconfig: config
        params:
          DEBUG: ((debug))
          LABEL_SELECTOR: release=service-catalog

      - task: install-service-broker
        file: ecs-broker-repo/ci/tasks/helm-cmd/task.yml
        input_mapping:
          kubeconfig: config
          values: broker-values
          charts: ecs-broker-repo/charts
        params:
          DEBUG: ((debug))
          IGNORE_ERROR: true
          COMMAND: install
          CHART: charts/
          VALUES: values/broker-values.yml
          RELEASE: ecs-service-broker

      - task: wait-until-ready
        file: ecs-broker-repo/ci/tasks/wait-until-ready/task.yml
        input_mapping:
          kubeconfig: config
        params:
          DEBUG: ((debug))
          LABEL_SELECTOR: release=ecs-service-broker

#      - task: create-bucket
#        file: ecs-broker-repo/tasks/broker-cmd #svcat cmd?
#
#      - task: test-bucket
#        file: ecs-broker-repo/tasks/broker-cmd #svcat cmd?
#
#      - task: delete-bucket
#        file: ecs-broker-repo/tasks/broker-cmd #svcat cmd?

      - put: docker_registry_dest
        params:
          image: docker_registry_src/image.tar

    on_success:
      put: slack-alert
      params:
        alert_type: success

    on_failure:
      put: slack-alert
      params:
        alert_type: failed

    on_abort:
      put: slack-alert
      params:
        alert_type: aborted

    on_error:
      put: slack-alert
      params:
        alert_type: custom
        message: Build Error
