---
platform: linux

image_resource:
  type: docker-image
  files:
  source:
    repository: bitnami/kubectl
    tag: 1.18.0

params:
  DEBUG:
  IGNORE_ERROR: false
  COMMAND:
  ARGS:
  K8S_CONFIG_FILE_NAME: config

inputs:
  - name: config
  - name: files
    optional: true

run:
  path: /bin/bash
  args:
    - -c
    - |
      if [[ $DEBUG == true ]]; then
        set -x
      fi

      if [[ $IGNORE_ERROR == true ]]; then
        set +e
      else
        set -e
      fi

      ARG_ARRAY=(${ARGS})
      kubectl --kubeconfig config/${K8S_CONFIG_FILE_NAME} ${COMMAND} "${ARG_ARRAY[@]}"

      exit 0
