---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bitnami/kubectl
    tag: 1.18.0

params:
  DEBUG:
  IGNORE_ERROR: false
  COMMAND:
  ARGS:
  K8S_CONFIG_FILE_NAME: config
  OUTPUT_FILE_NAME:

inputs:
  - name: project-repo
  - name: config
  - name: files
    optional: true

outputs:
  - name: output

run:
  path: project-repo/ci/tasks/kubectl-cmd/task.sh
