broker-config:
  managementEndpoint: https://127.0.0.1:4443
  namespace: ns1
  replicationGroup: urn:storageos:ReplicationGroupInfo:2ef0a92d-cf88-4933-90ba-90245aa031b1:global
  repositoryEndpoint: http://127.0.0.1:9020