apiVersion: v1
kind: ConfigMap
metadata:
  name: ecs-broker
data:
  application.yml: |-
    ---
    broker:
      prefix: {{ .Values.prefix }}
  {{- if eq (default "ECS" .Values.brokerMode) "ECS" }}
      object-endpoint: {{ .Values.api.endpoint }}
      management-endpoint: {{ .Values.ecsConnection.endpoint }}
      namespace: {{ .Values.namespace }}
      replication-group: {{ .Values.replicationGroup }}
  {{- end}}
  {{- if eq (default "ECS" .Values.brokerMode) "objectscale" }}
      apiType: "objectscale"
      accountId: {{ .Values.objectscale.account.id }}
      objectscale:
        id: {{ .Values.objectscale.id }}
        gatewayEndpoint: {{ .Values.objectscale.gatewayEndpoint }}
      objectstore:
        id: {{ .Values.objectstore.id }}
        name: {{ .Values.objectstore.name }}
        managementEndpoint: {{ .Values.objectstore.managementEndpoint }}
        s3Endpoint: {{ .Values.objectstore.s3Endpoint }}
  {{- end}}
  {{- if .Values.certificate }}
      certificate: {{ toYaml .Values.certificate | indent 6 }}
  {{- end }}
      ignoreSslValidation: {{ default false .Values.ignoreSslValidation }}
      defaultReclaimPolicy: {{ .Values.defaultReclaimPolicy }}
  {{- include "ecs-service-broker.catalog" . | indent 4 }}
    server:
      maxHttpHeaderSize: {{ default "32KB" .Values.tomcatMaxHttpHeaderSize}}
    spring:
      profiles: default
