apiVersion: v1
kind: ConfigMap
metadata:
  name: ecs-broker
data:
  application.yml: |-
    ---
    broker:
      object-endpoint: "http://10.243.86.70:9020"
      management-endpoint: "https://10.243.86.70:4443"
      namespace: "nightshift"
      replication-group: RG
      prefix: maddid-
      certificate: |-
        -----BEGIN CERTIFICATE-----
        MIIDCTCCAfGgAwIBAgIJAJ1g36y+tM0RMA0GCSqGSIb3DQEBCwUAMBQxEjAQBgNV
        BAMTCWxvY2FsaG9zdDAeFw0yMDAyMTkxOTMzMjVaFw0zMDAyMTYxOTMzMjVaMBQx
        EjAQBgNVBAMTCWxvY2FsaG9zdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
        ggEBAKdvGtq912EKCBNsHTYjtbRlDkJyietThHw7p3WQCUq+TBxSisPJCshWRbNr
        vpHjygnwZOSUcmvGdjpgXZeSUTWP0jgjCaOvhgeTHCRTKpkOd+tjEFpxCDGjZ61a
        wHWSzxHKKBCgd8v6ERgkUyaD7S6RaNVjZ6E49raiDqeGmTd1uQRVq8RzRy2HePiT
        G+rSRfS8qP3QzAjw1pIeJU100Ihy6wmMhUhmNJlU93INziF5mg0VYbnSW/bRb7zL
        tNVHI0jkgPDQvqPtf26TZAhIO1bBiWebEk9UUhzGtaNgFE6/k9NTpu7Z32zkvOFe
        vu7lw0x2c24p5mkPedycrGOGkHsCAwEAAaNeMFwwHwYDVR0jBBgwFoAU2us7uV9T
        ZvUaai/9XGPrjhRbKNswGgYDVR0RBBMwEYIJbG9jYWxob3N0hwR/AAABMB0GA1Ud
        DgQWBBTa6zu5X1Nm9RpqL/1cY+uOFFso2zANBgkqhkiG9w0BAQsFAAOCAQEAWcrd
        +6xY62Ctn+ijphaUOuH9GO1VCUjLRPwZc1/QfMLsss/UhJVITt7JhMMUjGcV5UyV
        JbQwoA+vso2DUbfehTceCWOa7QXLnO7si+ujVn0/vlCLvOj7MSJeRwOD3+3b2MpV
        AJImqfo4J7ovY4iYfKPLVO6l1B5N9Cw3F3ztcA3HfmtKS7pTA0H/TLxaJ8GVCQO+
        d+StKXhM4dLC/uyvkPRQhXifMYJB5WM5G1X+kaiD30kZ5R0oEyWmaDrkuy2Xy0AP
        4xCeTPYMHUQlqaUYYG4iNnMfdwJuBiTpEpxKN/zt1M+ycWXSyGSW/EkItxztO49v
        kQjNgkCo/artraBjvQ==
        -----END CERTIFICATE-----
    catalog:
      services:
      -
        active: true
        bindable: true
        description: "Elastic Cloud S3 Object Storage Bucket"
        id: f3cbab6a-5172-4ff1-a5c7-72990f0ce2aa
        repository-service: true
        metadata:
          displayName: ecs-bucket
          documentationUrl: "https://community.emc.com/docs/DOC-45012"
          imageUrl: "http://www.emc.com/images/products/header-image-icon-ecs.png"
          longDescription: "Dell EMC Elastic Cloud Storage (ECS) Object bucket for storing data using Amazon S3."
          providerDisplayName: "Dell EMC"
          supportUrl: "http://www.emc.com/products-solutions/trial-software-download/ecs.htm"
        name: ecs-bucket
        plan-updatable: true
        plans:
        -
          description: "Free Trial"
          free: true
          id: 8e777d49-0a78-4cf4-810a-b5f5173b019d
          metadata:
            bullets:
            - "Shared object storage"
            - "5 GB Storage"
            - "S3 protocol access"
            costs:
            -
              amount:
                usd: 0.0
              unit: MONTHLY
          name: 5gb
          service-settings:
            quota:
              limit: 5
              warn: 4
          repository-plan: true
        -
          description: "Pay per GB for Month"
          id: 89d20694-9ab0-4a98-bc6a-868d6d4ecf31
          metadata:
            bullets:
            - "Shared object storage"
            - "Unlimited Storage"
            - "S3 protocol access"
            costs:
            -
              amount:
                usd: 0.03
              unit: "PER GB PER MONTH"
          name: default
        service-settings:
          access-during-outage: true
          head-type: s3
          service-type: bucket
        tags:
        - s3
        - bucket
        type: bucket
      -
        active: false
        bindable: true
        description: "Elastic Cloud S3 Object Storage File Accessible Bucket"
        repository-service: false
        id: 9052313c-20b2-47de-900f-6e8b04fafcca
        metadata:
          displayName: ecs-file-bucket
          documentationUrl: "https://community.emc.com/docs/DOC-45012"
          imageUrl: "http://www.emc.com/images/products/header-image-icon-ecs.png"
          longDescription: "Dell EMC Elastic Cloud Storage (ECS) Object bucket for storing data using Amazon S3 or NFS."
          providerDisplayName: "Dell EMC"
          supportUrl: "http://www.emc.com/products-solutions/trial-software-download/ecs.htm"
        name: ecs-file-bucket
        plan-updatable: true
        plans:
        -
          description: "Free Trial"
          free: true
          id: b7c3f0b0-6867-44e3-b1b9-b255852010b3
          metadata:
            bullets:
            - "Shared object storage"
            - "5 GB Storage"
            - "S3 protocol and HDFS access"
            costs:
            -
              amount:
                usd: 0.0
              unit: MONTHLY
          name: 5gb
          service-settings:
            file-accessible: true
            quota:
              limit: 5
              warn: 4
        -
          description: "Pay per GB for Month"
          id: 285817bc-e73d-4bb4-bd5d-aebe54ef792f
          metadata:
            bullets:
            - "Shared object storage"
            - "Unlimited Storage"
            - "S3 protocol and HDFS access"
            costs:
            -
              amount:
                usd: 0.03
              unit: "PER GB PER MONTH"
          name: unlimited
        requires:
        - volume_mount
        service-settings:
          access-during-outage: true
          file-accessible: true
          head-type: s3
          service-type: bucket
        tags:
        - s3
        - bucket
        - nfs
        - hdfs
        type: bucket
    spring:
      profiles: default
