apiVersion: v1
kind: ConfigMap
metadata:
  name: ecs-broker
data:
  application.yml: |-
    ---
    broker:
      prefix: {{ .Values.prefix }}
      management-endpoint: {{ .Values.ecsConnection.managementEndpoint }}
      object-endpoint: {{ .Values.ecsConnection.s3endpoint }}
      namespace: {{ .Values.namespace }}
      replication-group: {{ .Values.replicationGroup }}
      awsSignatureV4: {{ default false .Values.ecsConnection.awsSignatureV4 }}
  {{- if .Values.certificate }}
      certificate: {{ toYaml .Values.certificate | indent 6 }}
  {{- end }}
      ignoreSslValidation: {{ default false .Values.ignoreSslValidation }}
      defaultReclaimPolicy: {{ .Values.defaultReclaimPolicy }}
  {{- include "ecs-service-broker.catalog" . | indent 4 }}
    server:
      maxHttpHeaderSize: {{ default "32KB" .Values.tomcatMaxHttpHeaderSize}}
    spring:
      profiles: default
