apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name }}-auth
data:
  username: {{ default "" .Values.api.username | b64enc | quote }}
  password: {{ default "" .Values.api.password | b64enc | quote }}

{{- if eq (default "ECS" .Values.brokerMode) "ECS" }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ecsConnection.name }}-auth
data:
  username: {{ default "" .Values.ecsConnection.username | b64enc | quote }}
  password: {{ default "" .Values.ecsConnection.password | b64enc | quote }}
{{- end}}
{{- if eq (default "ECS" .Values.brokerMode) "objectscale" }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.objectscale.id }}-auth
data:
  username: {{ default "" .Values.objectscale.managementUser.name | b64enc | quote }}
  password: {{ default "" .Values.objectscale.managementUser.password | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.objectscale.id }}-account-key
data:
  accessKey: {{ default "" .Values.objectscale.account.accessKey | b64enc | quote }}
  secretKey: {{ default "" .Values.objectscale.account.secretKey | b64enc | quote }}

{{- end }}
{{ if .Values.serviceCatalog }}
---

apiVersion: v1
kind: Secret
metadata:
  name: ecs-broker-catalog-credentials
type: Opaque
data:
  username: {{ randAlphaNum 10 | b64enc | quote }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
{{ end }}
